services:
  ansible-master:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    container_name: ansible-master
    volumes:
      - .:/ansible
    networks:
      - ansible-network
    depends_on:
      - node1
      - node2

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node1
    hostname: node1
    networks:
      - ansible-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node2
    hostname: node2
    networks:
      - ansible-network

networks:
  ansible-network:
    driver: bridge