# roles/common/tasks/main.yml
---
- name: Install common packages
  apt:
    name:
      - vim
      - curl
      - wget
      - htop
      - net-tools
    state: present
    update_cache: yes

- name: Set up timezone
  timezone:
    name: UTC

- name: Configure system limits
  template:
    src: templates/limits.conf.j2
    dest: /etc/security/limits.conf
  notify: restart sysctl